### ISSUE TITLE
Use @types/rdf-js typings

### ISSUE THREAD

**Issue by allforabit** [ontola/ontologies#10]
Hi, great and very useful idea for this library, thanks :-) 

I'm using a library node-quadstore and they seem to use https://www.npmjs.com/package/@types/rdf-js as the basis for their types. It would make it very smooth to interop between the this libary if it also used them if it was possible? Easy to enough to cast between them though.

**Comment by rescribet** [comment]
That package has seen been deprecated. 

Also, this package was intended as the other way round, so library and datamodel authors can safely swap between implementations without breaking much code.

Current plans for the next version is to include more control functions as part of the factory interface, so factories can be even more flexible in their modeling of the underlying data.
