### ISSUE TITLE
Licence not MIT?

### ISSUE THREAD

**Issue by flyon** [ontola/ontologies#14]
It's not quite "like Definitly Typed" , because that's MIT licenced. 
I'm not a lawyer, but I just saw this library is GPL-3, so believe I cannot use these ontologies in any software that I may want to sell?
Any reason why its not MIT?

**Comment by flyon** [comment]
ps. I've been reading into your reasons for changing some things of rdfjs, including potential webworker support. That aligns very much with me so I'd love to use & contribute to this library instead. But the license is a potential roadblock

**Comment by rescribet** [comment]
Fair enough https://github.com/ontola/ontologies/commit/8aad89b7ffd44e1e980f30229c81a13e8e89d646
